export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const CLEAR_USER_FETCH_ERROR_MSG = "CLEAR_USER_FETCH_ERROR_MSG";
export const FETCH_USERS_START = "FETCH_USERS_START";