// REDUX CONSTANTS
export const AUTH = "AUTH";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER = "REGISTER";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";
export const SELECTED_MOVIE = "SELECTED_MOVIE";
export const SELECTED_MOVIE_ERROR = "SELECTED_MOVIE_ERROR";
export const REVIEW_SUBMIT_SUCCESS = "REVIEW_SUBMIT_SUCCESS";
export const REVIEW_SUBMIT_FAILURE = "REVIEW_SUBMIT_SUCCESS";
export const REFRESH_REVIEW = "REFRESH_REVIEW";

export const FETCH_SCREENS = "FETCH_SCREENS";
export const CREATE_SCREEN = "CREATE_SCREEN";
export const EDIT_SCREEN = "EDIT_SCREEN";
export const FETCH_SCREENS_ERROR = "FETCH_SCREENS_ERROR";
export const CREATE_SCREEN_ERROR = "CREATE_SCREEN_ERROR";
export const EDIT_SCREEN_ERROR = "EDIT_SCREEN_ERROR";
export const SELECTED_SCREEN = "SELECTED_SCREEN";

export const FETCH_SHOWS = "FETCH_SHOWS";
export const CREATE_SHOW = "CREATE_SHOW";
export const FETCH_TIMINGS = "FETCH_TIMINGS";
export const FETCH_SHOWS_ERROR = "FETCH_SHOWS_ERROR";
export const CREATE_SHOW_ERROR = "CREATE_SHOW_ERROR";
export const FETCH_TIMINGS_ERROR = "FETCH_TIMINGS_ERROR";

// COMMON CONSTANTS
export const VISITOR = "VISITOR";
