export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAIL = "FETCH_MOVIE_FAIL";
export const FETCH_MOVIE_START = "FETCH_MOVIE_START";
export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const CLEAR_MOVIE_FETCH_ERROR_MSG = "CLEAR_MOVIE_FETCH_ERROR_MSG";