export const FETCH_SHOWS_SUCCESS = "FETCH_SHOWS_SUCCESS";
export const FETCH_SHOWS_FAIL = "FETCH_SHOWS_FAIL";
export const FETCH_SHOWS_START = "FETCH_SHOWS_START";
export const CLEAR_SHOW_FETCH_ERROR_MSG = "CLEAR_SHOW_FETCH_ERROR_MSG";
export const CREATE_SHOW_FAIL = "CREATE_SHOW_FAIL";
export const CREATE_SHOW_SUCCESS = "CREATE_SHOW_SUCCESS";
export const CLEAR_SHOW_MSG = "CLEAR_SHOW_MSG";