export const FETCH_SCREENS_SUCCESS = "FETCH_SCREENS_SUCCESS";
export const FETCH_SCREENS_FAIL = "FETCH_SCREENS_FAIL";
export const FETCH_SCREENS_START = "FETCH_SCREENS_START";
export const CLEAR_SCREEN_FETCH_ERROR_MSG = "CLEAR_SCREENS_FETCH_ERROR_MSG";
export const CREATE_SCREEN_SUCCESS = "CREATE_SCREEN_SUCCESS";
export const CREATE_SCREEN_FAIL = "CREATE_SCREEN_FAIL"; 